<div class="container">
	<div class="">
		<hr width="75%" color="#CFCFCF" />
		<div class="text-centered" >
			<p class="text-center">
			<small>powered by:</small><img class="" style="width:auto;height:150px;" src="res/img/mobwell_logo.png" />
</p>
		</div>
	</div>
</div>


						<!-- Include all compiled plugins (below), or include individual files as needed -->
						<script src="bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
						</body>
						</html>
